// فحص سريع: تقرير ملف الإنجاز الكامل (قالب متعدد الإنجازات) — قسم «الشواهد والمرفقات»
import { chromium } from 'playwright'
const BASE = process.env.BASE_URL || 'http://localhost:3000'
const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } })
const page = await ctx.newPage()
await page.goto(BASE)
await page.getByLabel('البريد الإلكتروني').fill('qa-patch-local@school.sa')
await page.locator('#login-password').fill('QaPatch!2026')
await page.getByRole('button', { name: 'تسجيل الدخول' }).click()
await page.waitForTimeout(3000)
await page.getByRole('navigation').getByRole('button', { name: 'التقارير' }).click()
await page.waitForTimeout(2200)
const card = page.locator('.group', { hasText: 'تقرير ملف الإنجاز الكامل' }).first()
await card.getByRole('button', { name: 'معاينة التقرير' }).click()
await page.waitForTimeout(9000)
const preview = page.locator('#report-preview-overlay')
const label = await preview.locator('text=الشواهد والمرفقات').count()
const img = await preview.locator('[data-rp-page] img').count()
const linkCard = await preview.locator('text=شاهد رابط:').count()
const pages = await preview.locator('[data-rp-page]').count()
console.log(`صفحات المعاينة = ${pages} | قسم «الشواهد والمرفقات» = ${label} | صور = ${img} | بطاقات روابط = ${linkCard}`)
await page.screenshot({ path: '/home/z/my-project/download/qa-full-report-evidence.png' })
await browser.close()
process.exit(label > 0 && img > 0 && linkCard > 0 ? 0 : 1)
